### ISSUE TITLE
Docs: Describe some use cases for Nodely

### ISSUE THREAD

**Issue by holyjak** [nubank/nodely#12]
Hello!

Nodely looks very interesting but I do not have a clear, concrete picture when and what for I would use it. I imagine you have concrete examples of what you use it for. It would be enlightening for me and surely others as well if you described those at the readme.

thank you!!!

**Comment by jtrunick** [comment]
@holyjak - You might look at the projects listed as "Related Work" to help answer your question.

**Comment by sovelten** [comment]
At Nubank we mainly use it for declaring and executing flows that have many outbound http requests. Those are the cases where we can benefit the most from async execution. It is also possible to use Nodely as a way to clearly separate between side effectful code and other computations.

There are most likely other uses to be found since Nodely solves a generic problem (declaring and running DAGs that support conditional declaration of data dependencies), we will be happy to hear if there are other people using Nodely in different scenarios.

You can also see the [tutorial](https://github.com/nubank/nodely/blob/main/samples/tutorial.clj) for simple examples.

There is also a [presentation](https://www.youtube.com/watch?v=oqE_aI26VrY) from London Clojurians
